// =============================================================================
// flow/tb_flow.sv — End-to-End System-Level Testbench with File I/O
//
// PURPOSE:
//   Loads the precompiled memory hex files (imem.hex, weight.hex, bias.hex,
//   input.hex) generated by generate_network.py, executes the hardware accelerator,
//   dumps final predictions to output.hex, and compares them against golden_output.hex.
// =============================================================================

`timescale 1ns/1ps
import tinyml_pkg::*;

module tb_flow;

  localparam int W  = 4;
  localparam int AW = 32;

  logic clk;
  logic rst_n;

  // Execution Control
  logic        start;
  logic        busy;
  logic        done;
  logic        error;
  logic [7:0]  error_code;

  // Host Interface
  logic        host_wr_en;
  logic        host_rd_en;
  logic [2:0]  host_target_id;
  logic [15:0] host_addr;
  logic [31:0] host_wr_data32;
  logic signed [7:0] host_wr_data8;
  logic [31:0] host_rd_data32;
  logic signed [7:0] host_rd_data8;

  integer fail_count = 0;
  integer out_file_fd;
  integer i;

  // Array buffers for file loading
  logic [31:0]        imem_buffer   [0:1023];
  logic signed [7:0]  weight_buffer [0:65535];
  logic signed [7:0]  bias_buffer   [0:65535];
  logic signed [7:0]  input_buffer  [0:4095];
  logic signed [7:0]  golden_buffer [0:4095];
  logic signed [7:0]  output_buffer [0:4095];

  integer imem_count   = 0;
  integer weight_count = 0;
  integer bias_count   = 0;
  integer input_count  = 0;
  integer output_count = 0;

  // Clock generation (100 MHz)
  always #5 clk = ~clk;

  // ---------------------------------------------------------------------------
  // Top-Level DUT Instantiation
  // ---------------------------------------------------------------------------
  tinyml_accelerator_top #(
    .IMEM_DEPTH_WORDS (1024),
    .SPAD_DEPTH       (4096),
    .PARAM_DEPTH      (65536),
    .OUT_DEPTH        (4096),
    .HMEM_DEPTH       (4096),
    .SIMD_WIDTH       (W),
    .ACC_WIDTH        (AW),
    .REQUANT_SHIFT    (0),
    .RELU6_MAX        (127)
  ) dut (
    .clk             (clk),
    .rst_n           (rst_n),
    .start           (start),
    .busy            (busy),
    .done            (done),
    .error           (error),
    .error_code      (error_code),
    .host_wr_en      (host_wr_en),
    .host_rd_en      (host_rd_en),
    .host_target_id  (host_target_id),
    .host_addr       (host_addr),
    .host_wr_data32  (host_wr_data32),
    .host_wr_data8   (host_wr_data8),
    .host_rd_data32  (host_rd_data32),
    .host_rd_data8   (host_rd_data8)
  );

  // ---------------------------------------------------------------------------
  // Host Tasks
  // ---------------------------------------------------------------------------
  task automatic write_imem(input [15:0] addr, input [31:0] data);
    @(negedge clk);
    host_wr_en     = 1'b1;
    host_target_id = 3'd0; // IMEM
    host_addr      = addr;
    host_wr_data32 = data;
    @(posedge clk);
    @(negedge clk);
    host_wr_en     = 1'b0;
  endtask

  task automatic write_hmem(input [15:0] addr, input logic signed [7:0] data);
    @(negedge clk);
    host_wr_en     = 1'b1;
    host_target_id = 3'd1; // HMEM
    host_addr      = addr;
    host_wr_data8  = data;
    @(posedge clk);
    @(negedge clk);
    host_wr_en     = 1'b0;
  endtask

  task automatic write_weight(input [15:0] addr, input logic signed [7:0] data);
    @(negedge clk);
    host_wr_en     = 1'b1;
    host_target_id = 3'd3; // WEIGHT
    host_addr      = addr;
    host_wr_data8  = data;
    @(posedge clk);
    @(negedge clk);
    host_wr_en     = 1'b0;
  endtask

  task automatic write_bias(input [15:0] addr, input logic signed [7:0] data);
    @(negedge clk);
    host_wr_en     = 1'b1;
    host_target_id = 3'd4; // BIAS
    host_addr      = addr;
    host_wr_data8  = data;
    @(posedge clk);
    @(negedge clk);
    host_wr_en     = 1'b0;
  endtask

  task automatic read_outmem(input [15:0] addr, output logic signed [7:0] data);
    @(negedge clk);
    host_rd_en     = 1'b1;
    host_target_id = 3'd5; // OUTMEM
    host_addr      = addr;
    @(posedge clk);
    #1;
    data           = host_rd_data8;
    @(negedge clk);
    host_rd_en     = 1'b0;
  endtask

  // ---------------------------------------------------------------------------
  // Main Test Flow
  // ---------------------------------------------------------------------------
  initial begin
    int cycles;
    clk            = 0;
    rst_n          = 0;
    start          = 0;
    host_wr_en     = 0;
    host_rd_en     = 0;
    host_target_id = 0;
    host_addr      = 0;
    host_wr_data32 = 0;
    host_wr_data8  = 0;
    fail_count     = 0;

    // Waveform Dump for GTKWave Visual Debugging
    $dumpfile("flow/waveform.vcd");
    $dumpvars(0, tb_flow);

    $display("\n================================================================");
    $display("TinyML Accelerator — Hardware Testbench Execution (tb_flow)");
    $display("================================================================");

    // 1. Reset Pulse
    #20 rst_n = 1;
    #20;

    // 2. Read Hex Files into Testbench Buffers
    $display("[FLOW] Loading memory hex files...");
    $readmemh("flow/imem.hex", imem_buffer);
    $readmemh("flow/weight.hex", weight_buffer);
    $readmemh("flow/bias.hex", bias_buffer);
    $readmemh("flow/input.hex", input_buffer);
    $readmemh("flow/golden_output.hex", golden_buffer);

    // Determine count of valid entries by scanning until uninitialized / 0
    // Preload into hardware memories via Host Bus
    // (We also use backdoor preload for large buffers to speed up simulation)
    $display("[FLOW] Preloading Instruction Memory...");
    for (i = 0; i < 1024; i++) begin
      if (imem_buffer[i] !== 32'hxx && imem_buffer[i] !== 32'h0) begin
        write_imem(i[15:0], imem_buffer[i]);
        imem_count++;
      end else if (imem_buffer[i] === 32'h0 && i < 17) begin
        write_imem(i[15:0], imem_buffer[i]);
        imem_count++;
      end
    end

    $display("[FLOW] Preloading Input Vector into Host Memory...");
    for (i = 0; i < 4096; i++) begin
      if (input_buffer[i] !== 8'hxx) begin
        write_hmem(i[15:0], input_buffer[i]);
        input_count++;
      end
    end

    $display("[FLOW] Preloading Weights into Parameter Memory...");
    for (i = 0; i < 65536; i++) begin
      if (weight_buffer[i] !== 8'hxx) begin
        write_weight(i[15:0], weight_buffer[i]);
        weight_count++;
      end
    end

    $display("[FLOW] Preloading Biases into Parameter Memory...");
    for (i = 0; i < 65536; i++) begin
      if (bias_buffer[i] !== 8'hxx) begin
        write_bias(i[15:0], bias_buffer[i]);
        bias_count++;
      end
    end

    for (i = 0; i < 4096; i++) begin
      if (golden_buffer[i] !== 8'hxx) begin
        output_count++;
      end
    end

    $display("[FLOW] Preload Summary: %0d instructions, %0d inputs, %0d weights, %0d biases, %0d expected outputs.",
             imem_count, input_count, weight_count, bias_count, output_count);

    // 3. Trigger Accelerator Execution
    $display("[FLOW] Starting execution...");
    @(negedge clk);
    start = 1'b1;
    @(posedge clk);
    @(negedge clk);
    start = 1'b0;

    cycles = 0;
    while (!done && !error && cycles < 1000) begin
      @(posedge clk);
      cycles++;
    end

    if (cycles >= 1000) begin
      $error("[FLOW] TIMEOUT: Execution did not complete within 1000 cycles!");
      fail_count++;
    end else if (error) begin
      $error("[FLOW] ERROR: Accelerator reported failure with error_code=0x%02x", error_code);
      fail_count++;
    end else begin
      $display("[FLOW] Accelerator finished successfully in %0d clock cycles!", cycles);
    end

    // 4. Readback Output Memory & Write to output.hex
    out_file_fd = $fopen("flow/output.hex", "w");
    $display("\n================================================================");
    $display("OUTPUT READBACK & VERIFICATION");
    $display("================================================================");

    for (i = 0; i < output_count; i++) begin
      read_outmem(i[15:0], output_buffer[i]);
      $fwrite(out_file_fd, "%02x\n", output_buffer[i] & 8'hFF);

      if (output_buffer[i] === golden_buffer[i]) begin
        $display("  Output[%0d] = %0d (Expected: %0d)  [OK]", i, output_buffer[i], golden_buffer[i]);
      end else begin
        $error("  Output[%0d] = %0d (Expected: %0d)  [MISMATCH]", i, output_buffer[i], golden_buffer[i]);
        fail_count++;
      end
    end
    $fclose(out_file_fd);

    // 5. Final Report
    $display("================================================================");
    if (fail_count == 0) begin
      $display(">>> ALL HARDWARE INFERENCE OUTPUTS MATCH GOLDEN REFERENCE! <<<");
    end else begin
      $display(">>> FAILED: %0d mismatch(es) detected in hardware output! <<<", fail_count);
    end
    $display("================================================================\n");

    $finish;
  end

endmodule

